'use strict';

var _ = require('lodash');
var React = require('react');


module.exports = function(brithon) {

	var ns = brithon.ns('core.server.views', {

		init: function() {
		},

		getHomePage: function() {
			return React.renderToStaticMarkup(
				<html>
					<head>
						<meta charSet='utf-8' />
					</head>
					<body>
						<p> This is generated by React. </p>
					</body>
				</html>
			);
		},

		getErrorPage: function(err) {
			return React.renderToStaticMarkup(
				<html>
					<head>
						<meta charSet='utf-8' />
					</head>
					<body>
						<p> {err.message} </p>
						<p> {err} </p>
					</body>
				</html>
			);
		}

	});

	return ns;
};