'use strict';

var _ = require('lodash');
var React = require('react');


module.exports = function(brithon) {

	var ns = brithon.ns('core.server.views', {

		init: function() {
		},

		getHomePage: function() {
			return React.renderToStaticMarkup(
				<html>
					<head>
						<meta charSet='utf-8' />
					</head>
					<body>
						<p> This is generated by React. </p>
					</body>
				</html>
			);
		},

		getErrorPage: function(error) {
			return React.renderToStaticMarkup(
				<html>
					<head>
						<meta charSet='utf-8' />
					</head>
					<body>
						<h1>{ error.message }</h1>
						<h2>{ error.status }</h2>
						<pre>{ error.stack }</pre>
					</body>
				</html>
			);
		}

	});

	return ns;
};